[2024-07-05T10:43:30.909+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T10:43:30.931+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prod_dag.run_postgre_docker manual__2024-07-05T10:43:15.493128+00:00 [queued]>
[2024-07-05T10:43:30.936+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prod_dag.run_postgre_docker manual__2024-07-05T10:43:15.493128+00:00 [queued]>
[2024-07-05T10:43:30.937+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-05T10:43:30.950+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_postgre_docker> on 2024-07-05 10:43:15.493128+00:00
[2024-07-05T10:43:30.956+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-05T10:43:30.957+0000] {standard_task_runner.py:63} INFO - Started process 293 to run task
[2024-07-05T10:43:30.958+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prod_dag', 'run_postgre_docker', 'manual__2024-07-05T10:43:15.493128+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/DAG_prod.py', '--cfg-path', '/tmp/tmpiiz9g5f1']
[2024-07-05T10:43:30.959+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask run_postgre_docker
[2024-07-05T10:43:31.025+0000] {task_command.py:426} INFO - Running <TaskInstance: prod_dag.run_postgre_docker manual__2024-07-05T10:43:15.493128+00:00 [running]> on host 39db74c4aadf
[2024-07-05T10:43:31.080+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prod_dag' AIRFLOW_CTX_TASK_ID='run_postgre_docker' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T10:43:15.493128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-05T10:43:15.493128+00:00'
[2024-07-05T10:43:31.081+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T10:43:31.103+0000] {docker.py:366} INFO - Starting docker container from image bost67dst/postgre_loading
[2024-07-05T10:51:45.795+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-05T10:51:45.796+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-05T10:51:45.797+0000] {process_utils.py:132} INFO - Sending 15 to group 293. PIDs of all processes in the group: [293]
[2024-07-05T10:51:45.797+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 293
[2024-07-05T10:51:45.797+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-05T10:51:45.798+0000] {docker.py:528} INFO - Stopping docker container
[2024-07-05T10:51:56.023+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T10:51:56.081+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=293, status='terminated', exitcode=0, started='10:43:30') (293) terminated with exit code 0
